import Head from 'next/head'
import styles from '../styles/App.module.css'
import App from '../components/App'

export default function Home() {
  return (
    <div className={styles.App}>
      {/* here this is the header which is where I put metada such as the title of the tab or the icon on the left of the tab etc... */}

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* here this is the main content of the app which is just the Signup component where all the other 5 components are rendered 
      with step to each one to simulate switching page when I hit the next button on each component*/}

      {/* That's why React.js/Next.js are really optimal and why coding with components is great, only one line of code here renders and displays all the content you see */}
      <App />
    </div>
  )
}
